#' @title abm_model_weights
#' @description model weights in 100 micro-calibration runs
#' @format A data frame with 75200 rows and 5 variables:
#' \describe{
#'   \item{\code{ID}}{double agent ID}
#'   \item{\code{w_q14}}{double financial weight}
#'   \item{\code{w_q45}}{double social weight}
#'   \item{\code{w_theta}}{double weight}
#'   \item{\code{calibration}}{double calibration run (1-100)}
#'}
#' @details generated by gen_model_ensemble()
"abm_weights_oo"
