#' @title empirical_utils_oo
#' @description empirical partial utilities for owner-occupiers. Initial bias-correction using epsilon=0.7.
#' @format A data frame with 1800 rows and 4 variables:
#' \describe{
#'   \item{\code{question_code}}{character COLUMN_DESCRIPTION}
#'   \item{\code{response_code}}{double COLUMN_DESCRIPTION}
#'   \item{\code{du_average}}{double mean utility}
#'   \item{\code{calibration}}{calibration run}
#'}
#' @details generated by get_model_ensemble()
"empirical_utils_oo"
